### ISSUE TITLE
Failed at the node-shared-cache@1.6.2 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by wxlworkhard** [kyriosli/node-shared-cache#10]

**Comment by mgttt** [comment]
on win xp/w2k3?

**Comment by z2014** [comment]
on Linux 2.6.32-431.20.3.el6.mt20140703.x86_64 also failed, what 's wrong?

**Comment by Dillybob1992** [comment]
Won't install on `node-v8.9.4`, unfortunately. Deletes the entire node_modules folder. Might have to use an older version. W7, 64-bit
