### ISSUE TITLE
Error trying to run example

### ISSUE THREAD

**Issue by richardgoater** [kyriosli/node-shared-cache#11]
```
Error: cache initialized with different size
```
Trying to run the example in the readme on Ubuntu 17.04 using node v8.1.2. Any ideas?

**Comment by kyriosli** [comment]
This error indicates that the memory region allocated has the right MAGIC code and a wrong size info. It may be initiated with different parameters. Could you give more information about which test code was ran? Or you can just free the pre-allocated memory by running `rm /run/shm/{cache_name}` or `/dev/shm/{}`.
Frankly by the way, I did't run it on node-v7 or higher platforms, so please be kind enough to supply more info.

**Comment by richardgoater** [comment]
Thanks very much for the quick reply, sir. The test I ran is as follows:
```JavaScript
var cache = require('node-shared-cache');
var obj = new cache.Cache("test", 512<<10);

// setting property
obj.foo = "bar";

// getting property
console.log(obj.foo);
```
amazingly this is working today without any changes. Deleting the shm entries helped when running the project tests. Sorry for wasting your time and thanks for your work, closing this issue.
