### ISSUE TITLE
Question/ Feature request - update event

### ISSUE THREAD

**Issue by fed135** [kyriosli/node-shared-cache#12]
First of all, this is an *amazing* library. I have many ideas of how I could leverage it for various things, like speeding up clustered http servers by using it like a redis message queue but unfortunatly it's missing one thing to fill my needs. Events.

Whenever a value is changed it would be nice to have an event dispatched, otherwise I 'm forced to do some polling.

Example usage:

`foo.on('update', (evt) => { console.log(evt.target.name, 'was updated'); });`

Would that be at all doable?

**Comment by kyriosli** [comment]
Hi, thanks for your concern and I appreciate for the idea you mentioned, but event dispatching is somehow not gonna be supported for a few reasons. The major problem is that we cannot discover a modification of a memory zone till we polled it.
