### ISSUE TITLE
Does this work on a Windows system?

### ISSUE THREAD

**Issue by dancrumb** [kyriosli/node-shared-cache#7]
I don't have a Windows system to check... but will this work? I'm trying to build something that works cross-platform

**Comment by matthias-christen** [comment]
Support for Windows was added. The version released on npm doesn't contain that code yet, though.

**Comment by dancrumb** [comment]
Great. Do you have an idea of when the update will be published?

**Comment by dancrumb** [comment]
Put more positively... is there anything I can do to help get this into a published version?

**Comment by kyriosli** [comment]
Ah, sorry about that. I did forgot to push it up to npm. Now I have uploaded it as a new version, and thank you again.
